
FROM node:10

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./
# ^^ This means that if package.json doesn't change, node_modules won't be reinstalled

RUN npm install -g react-scripts

USER node

RUN npm install

COPY --chown=node:node . .

CMD [ "npm", "start" ]