version: '3.1'

services:
  frontend:
    build: .
    volumes: 
      - './frontend:/app'
    ports:
      - '8081:8080'
    depends_on:
      - backend
  
  backend:
    build: .
    volumes:
      - './backend:/app'
    ports:
      - '3001:3000'
    depends_on:
      - wledb

  wledb:
    image: coryo12345/wledb:version1
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./docker/data/wledb:/var/lib/mysql